### PR TITLE
feat(comment): Users should comment on an article

### PR DESCRIPTION
**Pull request by Mirriam-Maina**
#### What does this PR do?
Enable users to create, retrieve, update and delete a comment to an article
Enable users to create, retrieve, update and delete a reply to a comment

#### Description of Task to be completed?
Users can view comments and comment threads

#### How should this be manually tested?
After cloning the repo, cd into it
Checkout the branch ```ft-comment-on-an-article-161255200```
Run ```npm install```
Run ```npm start```

#### What are the relevant pivotal tracker stories
[#161255200](https://www.pivotaltracker.com/story/show/161255200)

#### Screenshots
screen shot 2018-12-20 at 13 00 29

### CODE REVIEW

**Review by MartinKaburu — APPROVED** [review]
Looks very good to me.

**Review by mmosoroohh — APPROVED** [review]
@Mirriam-Maina I like the way you have comment on comment on a different section because it's easier to know the different types of comments on an article.

**Review by Tony-Ndichu — APPROVED** [review]
Looks good to me.

**Comment by mmosoroohh** [comment]
@Mirriam-Maina .... I can see you add comment text area covers end to end on the browser. I think that you should use the margin to reduce the width of your text area so that it's can on the center like you did on the view comment...

**Pull request merged**
