### PR TITLE
#161255190 Setup react router

### PR DESCRIPTION
**Pull request by Tony-Ndichu**
#### What does this PR do?

This PR sets up react router
#### Description of Task to be completed?

Setting up React router to enable routing
#### How should this be manually tested?

- Clone the repo: `git clone https://github.com/andela/ah-maps-frontend.git`
- Checkout to the branch: `git checkout ch-setup-react-router`
- Cd into the folder: `cd ah-maps-frontend`
- Install dependencies: `yarn`
- Run the tests: `yarn test`

#### What are the relevant pivotal tracker stories?

[#161255190](https://www.pivotaltracker.com/story/show/161255190)

### CODE REVIEW

**Review by p8ul — APPROVED** [review]
Looks cool, It is easy to add more routes. Clean and modular code

**Review by MartinKaburu — APPROVED** [review]
Great work.

**Comment by Rodgers-M** [comment]
@Tony-Ndichu you might need to update your `CSS` files to `sass`

**Review by mmosoroohh — APPROVED** [review]
looks good. Easy to follow through

**Review by Rodgers-M — APPROVED** [review]

**Pull request merged**
